spring:
  application:
    name: sika-learn
#  main:
#    lazy-initialization: true
  security:
    user:
      name: jermiel
      password: topsecret

management:
  endpoints:
    web:
      exposure:
        include: "*"
#        exclude: "health, info"
  info:
    env:
      enabled: true

info:
  app:
    name: My super goal
    description: A crazy fun app yoohoo !
    version: 1.0.0

# Define my own properties
coach:
  name: Mickey Mouse
team:
  name: The Mouse Club

# Change Spring Boot embedded server port
server:
  port: 7070
  servlet:
    context-path: /sikaseal
    session:
      timeout: 15m
